#pragma once
#include "ch.hpp"
#include "hal.h"
#define LOGGING_DRIVER SD2
#define SHELL_DRIVER LOGGING_DRIVER

#define LOGGING_TX_PIN PAL_LINE(GPIOA, 2U)
#define LOGGING_TX_PIN_MODE PAL_MODE_ALTERNATE(7)
#define LOGGING_RX_PIN PAL_LINE(GPIOA, 3U)
#define LOGGING_RX_PIN_MODE PAL_MODE_ALTERNATE(7)

// GPIO
#define LED_LINE PAL_LINE(GPIOB, 8U)
#define LED_LINE_MODE PAL_MODE_OUTPUT_PUSHPULL
